export const navLinks =[
    {
        name:'Home',
        link:'/home'
    },
    {
        name:'Nosotros',
        link:'/about'
    },
    {
        name:'Tours',
        link:'/tours'
    },
    {
        name:'Destinos',
        link:'/destinations'
    },
    {
        name:'Blog',
        link:'/blog'
    },
    {
        name:'Contactanos',
        link:'/contact'
    }
]